apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.castDb.pvc.claimName }}  # Dynamique via values.yaml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.castDb.pvc.size }}  # Dynamique via values.yaml
