apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.castService.serviceName }}
spec:
  selector:
    app: {{ .Values.castService.appLabel }}
  ports:
  - protocol: TCP
    port: {{ .Values.castService.servicePort }}  # Port externe exposé à l'extérieur du cluster
    targetPort: {{ .Values.castService.containerPort }}  # Port interne dans le conteneur
  type: ClusterIP
