apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nginx.configMapName }}"
# Pas besoin de spécifier 'namespace' ici, Kubernetes utilisera 'default' par défaut
data:
  nginx.conf: |
    server {
        listen 8081;

        location /api/v1/movies/docs {
            proxy_pass http://movie-service:8000/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/v1/casts/docs {
            proxy_pass http://cast-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
