apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.serviceName }}  # Nom dynamique
spec:
  selector:
    app: {{ .Values.nginx.appLabel }}    # Label dynamique pour associer au déploiement
  ports:
  - protocol: TCP
    port: {{ .Values.nginx.servicePort }}  # Port externe dynamique
    targetPort: {{ .Values.nginx.containerPort }}  # Port interne dynamique
  type: {{ .Values.nginx.serviceType }}    # Type de service dynamique
