apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.fastapiapp.service.port }}              # Port exposé par le service (externe)
      targetPort: {{ .Values.fastapiapp.service.targetPort }}   # Port cible dans le conteneur (interne)
      protocol: TCP
      name: http
  selector:
    {{- include "fastapiapp.selectorLabels" . | nindent 4 }}
